# This is a basic workflow to help you get started with Actions

name: Flutter With tmate

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with: { ref: pslab-demo }

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.3'
          channel: 'stable'

      - name: Flutter script
        working-directory: ./pslab_flutter_demo
        run: |
          echo 'flutter doctor' > script.sh
          echo 'flutter config --enable-macos-desktop --enable-ios --no-enable-linux-desktop --no-enable-windows-desktop --no-enable-android --no-enable-web' >> script.sh
          echo 'flutter build macos' >> script.sh
          echo 'flutter build ios --release --no-codesign' >>  script.sh

      - name: Start Mac VNC
        working-directory: ./pslab_flutter_demo
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -allowAccessFor -allUsers -privs -all
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvnclegacy -vnclegacy yes 
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvncpw -vncpw supersecret
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent -console
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
